version: "3.8"
services:
  frontend:
    build: ./docker-trial-frontend
    container_name: "frontend"
    ports:
      - "3000:3000"
    volumes:
      - "./docker-trial-frontend:/app"
  backend:
    build: ./docker-trial-backend
    container_name: "backend"
    ports:
      - "3001:3001"
    volumes:
      - "./docker-trial-backend:/app"
    # env_file:
    #   - ./docker-trial-backend/.env
